FROM newtmitch/sonar-scanner as sonarqube

WORKDIR /usr/src
COPY ./sonar-runner.properties /usr/lib/sonar-scanner/conf/sonar-scanner.properties
COPY --from=builder /usr/src/app/*.py ./
COPY --from=builder /usr/src/app/api ./api
RUN sonar-scanner -Dsonar.projectBaseDir=/usr/src
